image: codeminer42/ci-ruby:2.4

services:
  - postgres:latest

cache:
  key: Punchclock
  paths:
    - .gitlab-cache/

variables:
  RAILS_ENV: test
  DATABASE_URL: postgresql://postgres@postgres
  
before_script:
  - bundle install --without development production -j $(nproc) --path .gitlab-cache
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:create db:test:prepare
  - npm install
  - export DISPLAY=:99.0
  - wget -O /etc/init.d/xvfb https://gist.githubusercontent.com/axilleas/3fc13e0c90ad9f58bee903a41e8a6d48/raw/169a60010635e05eaa902c5f3b4393321f2452f0/xvfb
  - chmod 0755 /etc/init.d/xvfb
  - sh -e /etc/init.d/xvfb start

test:
  script:
    - bundle exec rake 
