image: codeminer/ruby:2.3

services:
  - postgres:latest

cache:
  key: Punchclock
  paths:
    - .gitlab-cache/

variables:
  RAILS_ENV: test
  DATABASE_URL: postgresql://postgres@postgres

before_script:
  - bundle install --without development production -j $(nproc) --path .gitlab-cache
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:create db:test:prepare

test:
  script:
    - bundle exec rspec -fd
