image: codeminer42/ci-ruby:2.5

stages:
  - test
  - security
  - deploy

services:
  - postgres:latest
cache:
  key: Punchclock-123u158
  paths:
  - .gitlab-cache/
variables:
  RAILS_ENV: test
  DATABASE_URL: postgresql://postgres@postgres
  CC_TEST_REPORTER_ID: 60f18b69ac3904ddf5b3875523d020e1ed419e3f3d4a3bfa0e81420e03615137
rspec:
  stage: test
  before_script:
    - apt-get -y update
    - apt-get -y install google-chrome-stable
    - bundle install --without development production -j $(nproc) --path .gitlab-cache
    - cp config/database.yml.example config/database.yml
    - bundle exec rake db:create db:test:prepare
    - npm install
    - bundle exec rake webpack:compile
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
  coverage: '/\((\d+.\d+%)\) covered/'
  script: bundle exec rake spec
  artifacts:
    paths:
      - coverage/index.html
    expire_in: 1 week
  after_script:
    - ./cc-test-reporter after-build --exit-code $?

brakeman:
  stage: security
  before_script:
    - bundle install
    - gem install brakeman
  script:
    - brakeman -z -q

bundler_audit:
  stage: security
  before_script:
    - gem install bundler-audit
  script: bundle audit

production:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --api-key=$HEROKU_PRODUCTION_API_KEY --app=punchlock
  only:
    - master
