image: codeminer42/ci-ruby:2.7

stages:
  - test
  - security
  - deploy

services:
  - postgres:latest
cache:
  key: ${CI_PROJECT_ID}
  paths:
    - vendor/ruby
    - node_modules/
    - .gitlab-cache/
    - .gems/
    - bin/cc-test-reporter
variables:
  RAILS_ENV: test
  DATABASE_URL: postgresql://postgres:postgres@postgres/punchclock_test
  CC_TEST_REPORTER_ID: 60f18b69ac3904ddf5b3875523d020e1ed419e3f3d4a3bfa0e81420e03615137
  POSTGRES_PASSWORD: postgres
  OTP_ENCRYPTION_KEY: 1ex1ex1ex1ex1ex1ex1ex1ex1ex1ex1ex1ex1ex1ex1ex1ex1e
rspec:
  stage: test
  before_script:
    - cp .env.example .env
    - gem install bundler
    - bundle config set path '.gems'
    - bundle config set without 'development production'
    - bundle install -j $(nproc)
    - bundle exec rake db:create db:test:prepare
    - npm install yarn --global
    - yarn install --frozen-lock
    - bundle exec rake webpacker:compile
    - '[ -f ./bin/cc-test-reporter ] || curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.6.3-linux-amd64 > ./bin/cc-test-reporter'
    - chmod +x ./bin/cc-test-reporter
    - ./bin/cc-test-reporter before-build
  coverage: '/\((\d+.\d+%)\) covered/'
  script: bundle exec rake spec
  only:
    - merge_requests
    - master
  artifacts:
    paths:
      - coverage/index.html
    expire_in: 1 week
  after_script:
    - ./bin/cc-test-reporter after-build --exit-code $?

brakeman:
  stage: security
  before_script:
    - gem i bundler
    - gem install brakeman
  script:
    - brakeman -z -q

bundler_audit:
  stage: security
  before_script:
    - gem install bundler-audit
    - bundle audit --update
  script: bundle audit

production:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --api-key=$HEROKU_PRODUCTION_API_KEY --app=punchlock
  when: manual
  only:
    - master
staging:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=punchclock-staging --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
    - master

