AllCops:
  Excludes:
    - 'gem/**'
    - 'db/**'
    - 'config/initializers/secret_token.rb'
Documentation:
  Enabled: false
ClassVars:
  Enabled: false
DotPosition:
  EnforcedStyle: leading
Layout/LineLength:
  Exclude:
   - spec/**/*

Metrics/BlockLength:
  Max: 99
  Exclude:
    - spec/**/*
Style/StringLiterals:
  Enabled: false
