version: '3.7'

services:
  app: &app
    build:
      context: .
    volumes:
      - .:/var/www/app
      - bundle_path:/bundle
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - REDIS_URL=redis://redis:6379/
      - DATABASE_URL=postgresql://postgres:postgres@postgres/punchclock_development
    depends_on:
      - postgres
      - redis
    tmpfs:
      - /tmp

  runner:
    <<: *app
    stdin_open: true
    tty: true
    command: /bin/bash
    networks:
      default:
      internal:

  runner_tests:
    <<: *app
    stdin_open: true
    tty: true
    command: echo "off by default"
    shm_size: '2gb'
    networks:
      default:
      internal:
    environment:
      - RAILS_ENV=${RAILS_ENV:-test}
      - DATABASE_URL=postgresql://postgres:postgres@postgres/punchclock_test

  server:
    <<: *app
    stdin_open: true
    tty: true
    command: bundle exec foreman start -f Procfile.dev
    networks:
      default:
      internal:
        aliases:
          - backend-server
    ports:
      - '5000:5000'
    env_file:
      - .env

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:6.2.4-buster
    volumes:
      - redis:/data
    ports:
      - 6379:6379

volumes:
  postgres:
  redis:
  bundle_path:

networks:
  internal:
