# config/application.yml
defaults: &defaults
  google_apps:
    domain: <%= ENV['GOOGLE_APPS_DOMAIN'] %>

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults