development:
  adapter: postgresql
  encoding: unicode
  database: punchclock_development
  pool: 5
  username: giovanni
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: punchclock_test
  pool: 5
  username: giovanni
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: punchclock_production
  pool: 5
  username: giovanni
  password:
