# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2983f9f4b48cb04a4c5a125c120fb7d7ec99f0a0081c8576eb4dc5dcf0921951a3df6c8b7aaad2c791559489856fc7650395877e76ca2d6e34c69bd68279e58e

test:
  secret_key_base: fc311756e45c70a5823c8d576d30788defe4330950d3a0f3f7e6e760588dcfee33c4ddbf6e4ee8b5e900e259995efb497ca176e9601808ec3afc0cb3810dbbcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
